# Generated by Django 5.2.8 on 2025-11-21 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "relationship_app",
            "0002_alter_author_id_alter_book_id_alter_librarian_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={
                "permissions": [
                    ("can_add_book", "Can add book"),
                    ("can_change_book", "Can change book"),
                    ("can_delete_book", "Can delete book"),
                ]
            },
        ),
    ]
