# Generated by Django 5.2.9 on 2025-12-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "posts",
                    models.ManyToManyField(
                        blank=True, related_name="tags", to="blog.post"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
